### ISSUE TITLE
Hand-in of assignment

### ISSUE THREAD

**Issue by Casper17-max** [isdsucph/isds2021#15]
Hi, 
Just to be sure: how should we hand in the assignment properly? 
Should we just download our answers as a Notebook (.ipynb format), and then upload it on Absalon under Assignment 0? 

/Casper

**Comment by joachimkrasmussen** [comment]
Hi Casper,

You should `do the following:
1. Click _kernel_ --> _restart and run all_ in order to (1) erase all your outputs, (2) re-create your outputs from the code that you have written, and (3) verify that everything looks like you expect.
2. Save this file as an `.ipynb` file and upload it on Absalon under assignment 0.

Does that make sense?

Best,
Joachim

**Comment by Casper17-max** [comment]
Yes, it does. Thank you :-) 
/Casper
